DROP TABLE EMPREGADO CASCADE CONSTRAINTS;
DROP TABLE DEPENDENTE CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE PROJETO CASCADE CONSTRAINTS;
DROP TABLE ALOCACAO CASCADE CONSTRAINTS;
